experiment:
  seed: 36
  device: "cuda:0"
  wandb: False
  wandb_api_key: ""
  wandb_project_name: "SimJEB_baseline"

dataset:
  data_dir: "/data/SimJEB/"
  max_epochs: 3000  
  train_sample_id: [21, 30, 38, 62, 8, 9, 15, 23, 6, 10, 22, 63, 14, 29, 35, 40, 19, 27, 28, 33]
  valid_sample_id: [20, 4, 0, 12, 16]

arch:
  encoder:
    n_layers_enc: 1
  processor: 
    hidden_dim: 64
    n_layers_pro: 10
  decoder:
    n_layers_dec: 1

scheduler:
  initial_lr: 5.E-4
  weight_decay: 0.05