experiment:
  seed: 36
  device: "cuda:2"
  wandb: False
  wandb_api_key: ""
  wandb_project_name: "SimJEB_vanilla GATr"

dataset:
  data_dir: "/data/SimJEB/"
  max_epochs: 200  
  train_sample_id: [21, 30, 38, 62, 8, 9, 15, 23, 6, 10, 22, 63, 14, 29, 35, 40, 19, 27, 28, 33]
  valid_sample_id: [20, 4, 0, 12, 16]

arch:
  encoder:
    in_mv_channel: 1
    in_s_channel: 2
  processor: 
    hidden_mv_channel: 4
    hidden_s_channel: 2
    n_layers_gatr: 8
    n_attn_heads: 8
  decoder:
    out_mv_channel: 1
    out_s_channel: 1

scheduler:
  initial_lr: 5.E-3
  weight_decay: 0.05