experiment:
  seed: 36
  device: "cuda:2"
  wandb: false
  wandb_api_key: "899079d77b6e3f0774afe79065ae85b86ac909d2"
  wandb_project_name: "baseline_EGNN"

dataset:
  data_dir: "/data/SimJEB/"
  max_epochs: 1000  
  train_sample_id: [21, 30, 38, 62, 8, 9, 15, 23, 6, 10, 22, 63, 14, 29, 35, 40, 19, 27, 28, 33]
  valid_sample_id: [20, 4, 0, 12, 16]

arch:
  encoder:
    input_dim: 2
  processor: 
    hidden_dim: 32
    n_layers_proc: 20
  decoder:
    output_dim: 1

scheduler:
  initial_lr: 5.E-6
  weight_decay: 0.0