_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 11
                - 49
                - 50
                - 55
                - 77
            "2":
                - 1
                - 11
                - 49
                - 50
                - 55
                - 77
            "3":
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.2
            "6": 4.47.1
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
